import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.css";
import { Nav } from "@/components/Nav/Nav";
import { CartProvider } from "@/components/Cart/cart-context";
import { cookies } from "next/headers";
import { getCart } from "@/lib/shopify";

const interTight = Inter_Tight({
  variable: "--interTight",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const cartId = cookies().get("cartId")?.value;
  const cartId = (await cookies()).get("cartId")?.value;
  const cart = getCart(cartId);

  return (
    <html lang='en'>
      <body className={`${interTight.variable}`}>
        <div
          style={{
            marginTop: "10rem",
          }}
        >
          <CartProvider cartPromise={cart}>
            <Nav />
            {children}
          </CartProvider>
        </div>
      </body>
    </html>
  );
}
